apiVersion: autoscaling/v2 
kind: HorizontalPodAutoscaler
metadata:
  name: backend-k8s
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend-k8s
  minReplicas: 1
  maxReplicas: 10000
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
